api_root_path: /
api_route: /ga4gh/drs/v1
auto_reload: true
aws_config_ini: null
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
db_connection_str: '**********'
db_name: dev_db
docs_url: /docs
drs_server_uri: drs://localhost:8080/
host: 127.0.0.1
log_level: info
openapi_url: /openapi.json
outbox_bucket: outbox
port: 8080
retry_access_after: 120
s3_access_key_id: test
s3_endpoint_url: http://dcs:4566
s3_secret_access_key: '**********'
s3_session_token: null
service_name: dcs
topic_name_drs_object_registered: drs-object-registered
topic_name_file_registered: file-internally-registered
topic_name_file_staged: file_staged_for_download
topic_name_stage_request: non_staged_file_requested
workers: 1
