api_root_path: /
api_route: /ga4gh/drs/v1
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  name: null
auth_key: '{"crv":"P-256","kty":"EC","x":"yBTtQdsuz8mav1MVYC6lk6MN9GJA30w6L2WOZywYZqE","y":"5HvxOSLXpdAGcnGl9OSe8j71OI7QAe_ZPubPdFDdGvQ"}'
auth_map_claims: {}
auto_reload: true
aws_config_ini: null
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
db_connection_str: '**********'
db_name: dev_db
docs_url: /docs
download_served_event_topic: file_downloads
download_served_event_type: donwload_served
drs_server_uri: drs://localhost:8080/
ekss_base_url: http://ekss:8080/
file_registered_event_topic: file_downloads
file_registered_event_type: file_registered
files_to_register_topic: internal_file_registry
files_to_register_type: file_registered
host: 127.0.0.1
kafka_servers:
- kafka:9092
log_level: info
openapi_url: /openapi.json
outbox_bucket: outbox
port: 8080
presigned_url_expires_after: 30
retry_access_after: 120
s3_access_key_id: test
s3_endpoint_url: http://dcs:4566
s3_secret_access_key: '**********'
s3_session_token: null
service_instance_id: '1'
service_name: dcs
unstaged_download_event_topic: file_downloads
unstaged_download_event_type: unstaged_download_requested
workers: 1
