components:
  schemas:
    AccessMethod:
      description: Wrapped DRS access_methods field value
      properties:
        access_url:
          $ref: '#/components/schemas/AccessURL'
        type:
          default: s3
          enum:
          - s3
          title: Type
          type: string
      required:
      - access_url
      title: AccessMethod
      type: object
    AccessURL:
      description: AccessUrl object for access method
      properties:
        url:
          title: Url
          type: string
      required:
      - url
      title: AccessURL
      type: object
    Checksum:
      description: Wrapped DRS checksums field value
      properties:
        checksum:
          title: Checksum
          type: string
        type:
          default: sha-256
          enum:
          - sha-256
          title: Type
          type: string
      required:
      - checksum
      title: Checksum
      type: object
    DeliveryDelayedModel:
      description: Pydantic model for 202 Response. Empty, since 202 has no body.
      properties: {}
      title: DeliveryDelayedModel
      type: object
    DrsObjectResponseModel:
      description: A DRS compliant representation for the DrsObjectWithAccess model
      properties:
        access_methods:
          items:
            $ref: '#/components/schemas/AccessMethod'
          title: Access Methods
          type: array
        checksums:
          items:
            $ref: '#/components/schemas/Checksum'
          title: Checksums
          type: array
        created_time:
          title: Created Time
          type: string
        id:
          title: Id
          type: string
        self_uri:
          title: Self Uri
          type: string
        size:
          title: Size
          type: integer
      required:
      - access_methods
      - checksums
      - created_time
      - id
      - self_uri
      - size
      title: DrsObjectResponseModel
      type: object
    EnvelopeEndpointErrorModel:
      description: Response model for 404 responses of the envelope endpoint
      discriminator:
        mapping:
          envelopeNotFoundError: '#/components/schemas/HttpEnvelopeNotFoundError'
          externalAPIError: '#/components/schemas/HttpExternalAPIError'
        propertyName: exception_id
      oneOf:
      - $ref: '#/components/schemas/HttpExternalAPIError'
      - $ref: '#/components/schemas/HttpEnvelopeNotFoundError'
      title: EnvelopeEndpointErrorModel
    EnvelopeResponseModel:
      description: Response model for base64 encoded envelope bytes
      properties:
        content:
          title: Content
          type: string
      required:
      - content
      title: EnvelopeResponseModel
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    HttpEnvelopeNotFoundError:
      additionalProperties: false
      description: A custom exception body model.
      properties:
        data:
          $ref: '#/components/schemas/HttpEnvelopeNotFoundErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          enum:
          - envelopeNotFoundError
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpEnvelopeNotFoundError
      type: object
    HttpEnvelopeNotFoundErrorData:
      description: 'An empty model used as default for describing exception data.

        Please overwrite this to define your own data model.'
      properties: {}
      title: HttpEnvelopeNotFoundErrorData
      type: object
    HttpExternalAPIError:
      additionalProperties: false
      description: A custom exception body model.
      properties:
        data:
          $ref: '#/components/schemas/HttpExternalAPIErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          enum:
          - externalAPIError
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpExternalAPIError
      type: object
    HttpExternalAPIErrorData:
      description: 'An empty model used as default for describing exception data.

        Please overwrite this to define your own data model.'
      properties: {}
      title: HttpExternalAPIErrorData
      type: object
    HttpObjectNotFoundError:
      additionalProperties: false
      description: A custom exception body model.
      properties:
        data:
          $ref: '#/components/schemas/HttpObjectNotFoundErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          enum:
          - noSuchObject
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpObjectNotFoundError
      type: object
    HttpObjectNotFoundErrorData:
      description: Model for exception data
      properties:
        object_id:
          title: Object Id
          type: string
      required:
      - object_id
      title: HttpObjectNotFoundErrorData
      type: object
    HttpTokenExpiredError:
      additionalProperties: false
      description: A custom exception body model.
      properties:
        data:
          $ref: '#/components/schemas/HttpTokenExpiredErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          enum:
          - tokenExpiredError
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpTokenExpiredError
      type: object
    HttpTokenExpiredErrorData:
      description: 'An empty model used as default for describing exception data.

        Please overwrite this to define your own data model.'
      properties: {}
      title: HttpTokenExpiredErrorData
      type: object
    HttpTokenMalformedError:
      additionalProperties: false
      description: A custom exception body model.
      properties:
        data:
          $ref: '#/components/schemas/HttpTokenMalformedErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          enum:
          - tokenMalformedError
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpTokenMalformedError
      type: object
    HttpTokenMalformedErrorData:
      description: 'An empty model used as default for describing exception data.

        Please overwrite this to define your own data model.'
      properties: {}
      title: HttpTokenMalformedErrorData
      type: object
    HttpTokenSignatureError:
      additionalProperties: false
      description: A custom exception body model.
      properties:
        data:
          $ref: '#/components/schemas/HttpTokenSignatureErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          enum:
          - tokenSignatureError
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpTokenSignatureError
      type: object
    HttpTokenSignatureErrorData:
      description: 'An empty model used as default for describing exception data.

        Please overwrite this to define your own data model.'
      properties: {}
      title: HttpTokenSignatureErrorData
      type: object
    HttpUserPubkeyMalformed:
      additionalProperties: false
      description: A custom exception body model.
      properties:
        data:
          $ref: '#/components/schemas/HttpUserPubkeyMalformedData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          enum:
          - userPubkeyMalformedError
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpUserPubkeyMalformed
      type: object
    HttpUserPubkeyMalformedData:
      description: 'An empty model used as default for describing exception data.

        Please overwrite this to define your own data model.'
      properties: {}
      title: HttpUserPubkeyMalformedData
      type: object
    TokenAuthenticationErrorModel:
      description: Response model for 403 responses due to issues with work order
        token processing
      discriminator:
        mapping:
          tokenExpiredError: '#/components/schemas/HttpTokenExpiredError'
          tokenMalformedError: '#/components/schemas/HttpTokenMalformedError'
          tokenSignatureError: '#/components/schemas/HttpTokenSignatureError'
        propertyName: exception_id
      oneOf:
      - $ref: '#/components/schemas/HttpTokenExpiredError'
      - $ref: '#/components/schemas/HttpTokenMalformedError'
      - $ref: '#/components/schemas/HttpTokenSignatureError'
      title: TokenAuthenticationErrorModel
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
  securitySchemes:
    HTTPBearer:
      scheme: bearer
      type: http
info:
  description: "A service managing access to file objects storedon an S3-compatible\
    \ Object Storage. \n\nThis is an implementation of the DRS standard from the Global\
    \ Alliance for Genomics and Health, please find more information at: https://github.com/ga4gh/data-repository-service-schemas"
  title: Download Controller Service
  version: 0.5.9
openapi: 3.0.2
paths:
  /health:
    get:
      description: Used to test if this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
      tags:
      - DownloadControllerService
  /objects/{object_id}:
    get:
      description: Get info about a ``DrsObject``.
      operationId: getDrsObject
      parameters:
      - in: path
        name: object_id
        required: true
        schema:
          title: Object Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DrsObjectResponseModel'
          description: The DrsObject was found successfully.
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryDelayedModel'
          description: The operation is delayed and will continue asynchronously.
            The client should retry this same request after the delay specified by
            Retry-After header.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenAuthenticationErrorModel'
          description: 'The request could not be processed due to issues with the
            work order tokenExceptions by ID:

            - tokenExpiredError: The provided token is no longer valid

            - tokenMalformedError: The token does not conform to the expected format

            - tokenSignatureError: Either the public key provided for validation is
            wrong or the token has been tampered with'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpObjectNotFoundError'
          description: 'Exceptions by ID:

            - noSuchObject: The requested DrsObject was not found'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Returns object metadata, and a list of access methods that can be used
        to fetch object bytes.
      tags:
      - DownloadControllerService
  /objects/{object_id}/envelopes:
    get:
      description: 'Retrieve the base64 encoded envelope for a given object based
        on object id and

        URL safe base64 encoded public key'
      operationId: getEnvelope
      parameters:
      - in: path
        name: object_id
        required: true
        schema:
          title: Object Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvelopeResponseModel'
          description: Successfully delivered envelope.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpUserPubkeyMalformed'
          description: 'The request could not be processed as the user public key
            included in the work order token is malformedExceptions by ID:

            - userPubkeyMalformedError: User pubkey is empty/missing or cannot be
            decoded'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenAuthenticationErrorModel'
          description: 'The request could not be processed due to issues with the
            work order tokenExceptions by ID:

            - tokenExpiredError: The provided token is no longer valid

            - tokenMalformedError: The token does not conform to the expected format

            - tokenSignatureError: Either the public key provided for validation is
            wrong or the token has been tampered with'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvelopeEndpointErrorModel'
          description: 'Exceptions by ID:

            - envelopeNotFoundError: The requested envelope could not be retrieved

            - noSuchObject: The requested DrsObject was not found'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpExternalAPIError'
          description: 'Exceptions by ID:

            - externalAPIError: Communication with a service external API failed'
      security:
      - HTTPBearer: []
      summary: Returns base64 encoded, personalized file envelope
      tags:
      - DownloadControllerService
servers:
- url: /ga4gh/drs/v1
tags:
- name: DownloadControllerService
