name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - uses: actions/checkout@v3

      - id: common
        uses: ghga-de/gh-action-common@v3

      - name: Run pytest
        run: |
          pip uninstall dcs
          pip install -y ./src
          pytest \
            --cov=./src

      # - id: coveralls
      #   name: Upload coverage to coveralls
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     pip install --upgrade coveralls
      #     coveralls --service=github
